language: java
jdk:
  - oraclejdk8

install: ant
script: ant test

notifications:
 email:
    recipients:
      - aguscambiano@gmail.com
      - ivan.soriano@live.com.ar
    on_failure: always
    on_success: always

